# Generated by Django 3.1 on 2021-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210204_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default='APPROVED', max_length=50),
        ),
    ]
